### ISSUE TITLE
Menu items komen niet na registratie

### ISSUE THREAD

**Issue by Pietbel17** [robinvdijk/energybattle#17]
Als je ingelogd bent via facebook, en je hebt geen persoonlijke gegevens ingevuld (in het tweede scherm) dan kan je wel door klikken. (is al de eerste fout!)
Als je vervolgens doorklikt verschijnen er geen menu-items. Waarschijnlijk omdat je geen gegevens ingevuld hebt.

**Comment by robinvdijk** [comment]
Dit is gefixt. Wordt meegestuurd wanneer ik mijn overige code verstuur.
